/*
*
* MEDIALIVE constants
*
*/

export const DEFAULT_ACTION = "app/MediaLive/DEFAULT_ACTION";

// Constant for MediaLive
export const MEDIALIVE_CONST_ADD_AWS_GET =
  "app/MEDIALIVE/MEDIALIVE_CONST_ADD_AWS_GET";
export const MEDIALIVE_CONST_ADD_AWS_GET_SUCCESS =
  "app/MEDIALIVE/MEDIALIVE_CONST_ADD_AWS_GET_SUCCESS";
export const MEDIALIVE_CONST_ADD_AWS_GET_ERROR =
  "app/MEDIALIVE/MEDIALIVE_CONST_ADD_AWS_GET_ERROR";
export const MEDIALIVE_CONST_ADD = "app/MediaLive/MEDIALIVE_CONST_ADD";
export const MEDIALIVE_CONST_ADD_POST =
  "app/MediaLive/MEDIALIVE_CONST_ADD_POST";
export const MEDIALIVE_CONST_ADD_SUCCESS =
  "app/MediaLive/MEDIALIVE_CONST_ADD_SUCCESS";
export const MEDIALIVE_CONST_ADD_ERROR =
  "app/MediaLive/MEDIALIVE_CONST_ADD_ERROR";
export const MEDIALIVE_CONST_ADD_AWS_POST =
  "app/MediaLive/MEDIALIVE_CONST_ADD_AWS_POST";
export const MEDIALIVE_CONST_ADD_AWS_SUCCESS =
  "app/MediaLive/MEDIALIVE_CONST_ADD_AWS_SUCCESS";
export const MEDIALIVE_CONST_ADD_AWS_ERROR =
  "app/MediaLive/MEDIALIVE_CONST_ADD_AWS_ERROR";
export const MEDIALIVE_CONST_ADD_MODEL =
  "app/MediaLive/MEDIALIVE_CONST_ADD_MODEL";
export const MEDIALIVE_CONST_ADD_FORM_STRUCTURE =
  "app/MediaLive/MEDIALIVE_CONST_ADD_FORM_STRUCTURE";
export const MEDIALIVE_CONST_ADD_FORM_INPUT =
  "app/MediaLive/MEDIALIVE_CONST_ADD_FORM_INPUT";
export const MEDIALIVE_CONST_ADD_FORM_RESET =
  "app/MediaLive/MEDIALIVE_CONST_ADD_FORM_RESET";
