/*
*
* CRUD constants
*
*/

export const DEFAULT_ACTION = "app/Crud/DEFAULT_ACTION";

// Constant for loading API Data

export const CRUD_CONST_APIDATA = "app/Crud/CRUD_CONST_APIDATA";
export const CRUD_CONST_APIDATA_SUCCESS = "app/Crud/CRUD_CONST_APIDATA_SUCCESS";
export const CRUD_CONST_APIDATA_ERROR = "app/Crud/CRUD_CONST_APIDATA_ERROR";

// Contstants for CRUD Operations
export const CRUD_CONST_CREATE = "app/Crud/CRUD_CONST_CREATE";
export const CRUD_CONST_CREATE_SUCCESS = "app/Crud/CRUD_CONST_CREATE_SUCCESS";
export const CRUD_CONST_CREATE_ERROR = "app/Crud/CRUD_CONST_CREATE_ERROR";

export const CRUD_CONST_READ = "app/Crud/CRUD_CONST_READ";
export const CRUD_CONST_READ_SUCCESS = "app/Crud/CRUD_CONST_READ_SUCCESS";
export const CRUD_CONST_READ_ERROR = "app/Crud/CRUD_CONST_READ_ERROR";

export const CRUD_CONST_UPDATE = "app/Crud/CRUD_CONST_UPDATE";
export const CRUD_CONST_UPDATE_SUCCESS = "app/Crud/CRUD_CONST_UPDATE_SUCCESS";
export const CRUD_CONST_UPDATE_ERROR = "app/Crud/CRUD_CONST_UPDATE_ERROR";

export const CRUD_CONST_UPDATE_ITEM = "app/Crud/CRUD_CONST_UPDATE_ITEM";
export const CRUD_CONST_UPDATE_ITEM_SUCCESS = "app/Crud/CRUD_CONST_UPDATE_ITEM_SUCCESS";
export const CRUD_CONST_UPDATE_ITEM_ERROR = "app/Crud/CRUD_CONST_UPDATE_ITEM_ERROR";

export const CRUD_CONST_DELETE = "app/Crud/CRUD_CONST_DELETE";
export const CRUD_CONST_DELETE_SUCCESS = "app/Crud/CRUD_CONST_DELETE_SUCCESS";
export const CRUD_CONST_DELETE_ERROR = "app/Crud/CRUD_CONST_DELETE_ERROR";

