/*
*
* BOOK constants
*
*/

export const DEFAULT_ACTION = "app/Book/DEFAULT_ACTION";

// Constant for loading API Data

export const BOOK_CONST_APIDATA = "app/Book/BOOK_CONST_APIDATA";
export const BOOK_CONST_APIDATA_SUCCESS = "app/Book/BOOK_CONST_APIDATA_SUCCESS";
export const BOOK_CONST_APIDATA_ERROR = "app/Book/BOOK_CONST_APIDATA_ERROR";

export const BOOK_CONST_CREATE_CHANNEL = "app/Book/BOOK_CONST_CREATE_CHANNEL";
export const BOOK_CONST_CREATE_CHANNEL_SUCCESS =
  "app/Book/BOOK_CONST_CREATE_CHANNEL_SUCCESS";
export const BOOK_CONST_CREATE_CHANNEL_ERROR =
  "app/Book/BOOK_CONST_CREATE_CHANNEL_ERROR";

export const BOOK_CONST_CREATE_INPUT = "app/Book/BOOK_CONST_CREATE_INPUT";
export const BOOK_CONST_START_STREAM = "app/Book/BOOK_CONST_START_STREAM";
export const BOOK_CONST_STOP_STREAM = "app/Book/BOOK_CONST_STOP_STREAM";
